<Project Sdk="Aspire.AppHost.Sdk/13.6.0">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>aspire-field-notes-catalog-13-6</UserSecretsId>
    <AspireUseCliBundle>true</AspireUseCliBundle>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.6.0" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.6.0" />
    <PackageReference Include="Aspire.Hosting.Docker" Version="13.6.0" />
    <ProjectReference Include="../Catalog.Api/Catalog.Api.csproj" />
    <ProjectReference Include="../Inventory.Api/Inventory.Api.csproj" />
  </ItemGroup>
</Project>
